# Generated by Django 2.1.dev20170922165119 on 2017-11-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='appmessage',
            name='whoRecv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoRecv', to='home.AppUser'),
        ),
        migrations.AddField(
            model_name='appmessage',
            name='whoSent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoSent', to='home.AppUser'),
        ),
    ]
