# Generated by Django 2.1.dev20170922165119 on 2017-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image_url',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
