# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='model_pic',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder/'),
        ),
    ]
