# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appuser_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='model_pic',
            field=models.ImageField(default=b'no-img.jpg', upload_to=b'static/'),
        ),
    ]
